theme: jekyll-theme-minimal
navigation:
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
  - title: "Notes"
    url: "/notes"  # The new section for your notes
  - title: "Misc"
    url: "/misc"
